import type { RiskItem } from './riskTypes';

// Mock risks. Replace with exact entries from your image when available.
export const riskSeeds: RiskItem[] = [
  {
    id: 'RISK-1501',
    category: 'Security',
    title: 'Unpatched edge nodes',
    ticket: 'RISK-233',
    client: 'Global Edge',
    owner: 'J. Chen',
    status: 'Open',
    priority: 'High',
    impact: 'High',
    likelihood: 'Likely',
    date: '2025-08-10',
    briefDescription: 'Several edge nodes are running outdated OpenSSL builds.',
    analysis: 'Exposure on internet-facing nodes increases compromise likelihood. Patch window needs coordination.',
    tags: ['openssl', 'edge', 'patching'],
    mitigations: [],
    nextReviewDue: '2025-08-20',
  },
  {
    id: 'RISK-1502',
    category: 'Reliability',
    title: 'Build agents single point of failure',
    ticket: 'RISK-221',
    client: 'Core Platform',
    owner: 'S. Brooks',
    status: 'In Review',
    priority: 'Medium',
    impact: 'Medium',
    likelihood: 'Possible',
    date: '2025-08-01',
    briefDescription: 'Only one build agent pool in production region.',
    analysis: 'Agent outages will block deployments. Consider horizontal scaling and regional redundancy.',
    tags: ['ci', 'deployment'],
    mitigations: [],
    nextReviewDue: '2025-08-22',
  },
  {
    id: 'RISK-1503',
    category: 'Compliance',
    title: 'PII retention beyond policy',
    client: 'Apex Health',
    owner: 'A. Patel',
    status: 'Mitigating',
    priority: 'High',
    impact: 'High',
    likelihood: 'Unlikely',
    date: '2025-07-28',
    briefDescription: 'Legacy logs store PII longer than 30 days.',
    analysis: 'Potential audit failure. Need lifecycle rules and backfill cleanup.',
    tags: ['pii', 'retention'],
    mitigations: [
      { id: 'm1', title: 'Add S3 lifecycle rules', owner: 'Ops', dueDate: '2025-08-18', status: 'In Progress' },
    ],
    nextReviewDue: '2025-08-18',
  },
  {
    id: 'RISK-1504',
    category: 'Performance',
    title: 'Checkout latency under peak',
    client: 'Nordic Freight',
    owner: 'P. Gomez',
    status: 'Open',
    priority: 'Low',
    impact: 'Low',
    likelihood: 'Almost Certain',
    date: '2025-08-11',
    briefDescription: 'P95 latency spikes during end-of-month closing.',
    analysis: 'Thundering herd on DB writer; add caching and queue backpressure.',
    tags: ['latency', 'cache'],
    mitigations: [],
    nextReviewDue: '2025-08-30',
  },
];


